### ISSUE TITLE
where is wingardium leviosa?

### ISSUE THREAD

**Issue by powerdollkirby** [P-Y-R-O-B-O-T/HARRY_POTTER_ALIASES#2]
![kutsd9a4etvc1](https://github.com/P-Y-R-O-B-O-T/HARRY_POTTER_ALIASES/assets/105698999/40cfe901-fb70-4522-93a3-0f9154b9c583)

**Comment by P-Y-R-O-B-O-T** [comment]
Added in mapping.rc but forgot to add in readme, will add it asap, thanks for noticing. 😅
